%% load in the data
load('expCountClusters_data.mat');

%% Build error bar plot of STD of CDC14-GFP Signal Intensities
figure;
bar([mean(wtStdArray); mean(fob1StdArray); mean(hmo1StdArray)],...
    'FaceColor', [0.8, 0.8, 0.8]);
hold on;
errorbar([mean(wtStdArray);...
    mean(fob1StdArray);...
    mean(hmo1StdArray)],...
    [std(wtStdArray)/sqrt(numel(wtStdArray));...
    std(fob1StdArray)/sqrt(numel(wtStdArray));...
    std(hmo1StdArray)/sqrt(numel(wtStdArray))],...
    'LineStyle', 'none',...
    'Marker', 'none',...
    'Color', 'black',...
    'LineWidth', 2);
hold off;
set(gca,'TickLabelInterpreter', 'tex');
set(gca,'xticklabel',{'WT','{\it fob1}\Delta','{\it hmo1}\Delta'});
ylabel('signal STD');
%% Build error bar plot of cluster number
figure;
bar([mean(wtClusterArray); mean(fob1ClusterArray); mean(hmo1ClusterArray)],...
    'FaceColor', [0.8, 0.8, 0.8]);
hold on;
errorbar([mean(wtClusterArray);...
    mean(fob1ClusterArray);...
    mean(hmo1ClusterArray)],...
    [std(wtClusterArray)/sqrt(numel(wtClusterArray));...
    std(fob1ClusterArray)/sqrt(numel(wtClusterArray));...
    std(hmo1ClusterArray)/sqrt(numel(wtClusterArray))],...
    'LineStyle', 'none',...
    'Marker', 'none',...
    'Color', 'black',...
    'LineWidth', 2);
hold off;
set(gca,'TickLabelInterpreter', 'tex');
set(gca,'xticklabel',{'WT','{\it fob1}\Delta','{\it hmo1}\Delta'});
ylabel('number of clusters');
%% Area plots
clear;
load('expAreaCompare.mat');
figure;
bar([mean(wtArea)*0.0645^2; mean(fob1Area)*0.0645^2; mean(hmo1Area)*0.0645^2],...
    'FaceColor', [0.8, 0.8, 0.8]);
hold on;
errorbar([mean(wtArea*0.0645^2);...
    mean(fob1Area*0.0645^2);...
    mean(hmo1Area*0.0645^2)],...
    [std(wtArea)*0.0645^2/sqrt(numel(wtArea));...
    std(fob1Area)*0.0645^2/sqrt(numel(wtArea));...
    std(hmo1Area)*0.0645^2/sqrt(numel(wtArea))],...
    'LineStyle', 'none',...
    'Marker', 'none',...
    'Color', 'black',...
    'LineWidth', 2);
hold off;
set(gca,'TickLabelInterpreter', 'tex');
set(gca,'xticklabel',{'WT','{\it fob1}\Delta','{\it hmo1}\Delta'});
ylabel('signal area (\mum)')